[package]
name = "hp_statistic"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json="1.0.149"
chrono = "0.4"
tesseract_lib = { path = "../tesseract_lib" }
