[package]
name = "mmr_libs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.version = "1.49.0"
tokio.features = [ "rt", "rt-multi-thread", "macros", "fs", "io-util", "sync"]
flume = "0.12.0"
